"""Tests for dataset-record filtering."""

from nanomind_slm.data.filtering import (
    evaluate_common_requirements,
    evaluate_quality_requirements,
)

ALLOWED_LICENSES = {
    "apache-2.0",
    "mit",
    "bsd-2-clause",
    "bsd-3-clause",
}


def make_record(**changes: object) -> dict[str, object]:
    """Create a small artificial record for testing."""
    record: dict[str, object] = {
        "content": "def add(a, b):\n    return a + b\n",
        "license": "mit",
        "autogenerated": False,
    }
    record.update(changes)
    return record


def quality_decision(
    record: dict[str, object],
):
    """Apply consistent quality settings during tests."""
    return evaluate_quality_requirements(
        record,
        ALLOWED_LICENSES,
        min_characters=10,
        max_characters=100,
        max_line_length=50,
        allow_autogenerated=False,
    )


def test_common_filter_accepts_permissive_license() -> None:
    decision = evaluate_common_requirements(
        make_record(),
        ALLOWED_LICENSES,
    )

    assert decision.accepted is True
    assert decision.reason == "accepted"


def test_common_filter_rejects_disallowed_license() -> None:
    decision = evaluate_common_requirements(
        make_record(license="gpl-3.0"),
        ALLOWED_LICENSES,
    )

    assert decision.accepted is False
    assert decision.reason == "license_not_allowed"


def test_quality_filter_rejects_short_content() -> None:
    decision = quality_decision(make_record(content="x = 1"))

    assert decision.accepted is False
    assert decision.reason == "content_too_short"


def test_quality_filter_rejects_large_content() -> None:
    decision = quality_decision(make_record(content="x" * 101))

    assert decision.accepted is False
    assert decision.reason == "content_too_long"


def test_quality_filter_rejects_autogenerated_content() -> None:
    decision = quality_decision(make_record(autogenerated=True))

    assert decision.accepted is False
    assert decision.reason == "autogenerated"


def test_quality_filter_rejects_long_line() -> None:
    decision = quality_decision(make_record(content="x" * 51))

    assert decision.accepted is False
    assert decision.reason == "line_too_long"


def test_quality_filter_accepts_valid_content() -> None:
    decision = quality_decision(make_record())

    assert decision.accepted is True
    assert decision.reason == "accepted"
