"""Compare baseline and quality filters on a bounded dataset stream."""

from collections import Counter
from itertools import islice
from pathlib import Path
from typing import Any

import yaml
from datasets import IterableDataset, load_dataset

from nanomind_slm.data.filtering import (
    evaluate_common_requirements,
    evaluate_quality_requirements,
)

CONFIG_PATH = Path("configs/data.yaml")


def load_config() -> dict[str, Any]:
    """Load the dataset configuration."""
    with CONFIG_PATH.open(encoding="utf-8") as file:
        config = yaml.safe_load(file)

    if not isinstance(config, dict):
        raise TypeError("Dataset configuration must be a dictionary.")

    return config


def print_results(
    name: str,
    counts: Counter[str],
    total: int,
) -> None:
    """Print acceptance and rejection counts."""
    accepted = counts["accepted"]
    rejected = total - accepted
    acceptance_rate = accepted / total * 100 if total else 0.0

    print(f"\n{name}")
    print(f"  accepted: {accepted}")
    print(f"  rejected: {rejected}")
    print(f"  acceptance rate: {acceptance_rate:.2f}%")
    print("  decision reasons:")

    for reason, count in counts.most_common():
        print(f"    {reason}: {count}")


def main() -> None:
    """Compare both filters using the same bounded records."""
    config = load_config()

    dataset_config = config["dataset"]
    audit_config = config["audit"]
    license_config = config["license_policy"]
    filter_config = config["filtering"]

    dataset_id = str(dataset_config["id"])
    split = str(dataset_config["split"])
    streaming = dataset_config["streaming"]
    sample_limit = int(audit_config["sample_limit"])

    if streaming is not True:
        raise ValueError("Dataset streaming must be enabled.")

    if sample_limit < 1 or sample_limit > 1000:
        raise ValueError("Audit sample_limit must be between 1 and 1000.")

    allowed_licenses = {str(item) for item in license_config["allow"]}

    baseline_counts: Counter[str] = Counter()
    quality_counts: Counter[str] = Counter()
    observed_count = 0

    print(f"Dataset: {dataset_id}")
    print(f"Maximum records: {sample_limit}")
    print("Streaming: enabled")
    print("Source-code printing: disabled")
    print("Raw-file storage: disabled")

    dataset = load_dataset(
        dataset_id,
        split=split,
        streaming=True,
    )

    if not isinstance(dataset, IterableDataset):
        raise TypeError("Expected a streaming IterableDataset.")

    for record in islice(dataset, sample_limit):
        observed_count += 1

        baseline_decision = evaluate_common_requirements(
            record,
            allowed_licenses,
        )
        baseline_counts[baseline_decision.reason] += 1

        quality_decision = evaluate_quality_requirements(
            record,
            allowed_licenses,
            min_characters=int(filter_config["min_characters"]),
            max_characters=int(filter_config["max_characters"]),
            max_line_length=int(filter_config["max_line_length"]),
            allow_autogenerated=bool(filter_config["allow_autogenerated"]),
        )
        quality_counts[quality_decision.reason] += 1

    if observed_count != sample_limit:
        raise RuntimeError(f"Expected {sample_limit} records, received {observed_count}.")

    print_results("Baseline filter", baseline_counts, observed_count)
    print_results("Quality filter", quality_counts, observed_count)

    if quality_counts["accepted"] > baseline_counts["accepted"]:
        raise RuntimeError("Quality filter accepted more records than the baseline.")

    print("\nFilter comparison audit: PASSED")


if __name__ == "__main__":
    main()
