"""Build bounded streamed corpora for baseline and quality tokenizers."""

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from datasets import load_dataset

from nanomind_slm.data.filtering import (
    evaluate_common_requirements,
    evaluate_quality_requirements,
)
from nanomind_slm.data.sampling import assign_split


@dataclass
class CorpusState:
    path: Path
    max_records: int
    max_characters: int
    records: int = 0
    characters: int = 0

    def add(self, content: str) -> bool:
        if self.records >= self.max_records:
            return False

        if self.characters + len(content) > self.max_characters:
            return False

        with self.path.open("a", encoding="utf-8") as file:
            file.write(content.rstrip())
            file.write("\n\n")

        self.records += 1
        self.characters += len(content)
        return True


def main() -> None:
    with Path("configs/data.yaml").open(encoding="utf-8") as file:
        config: dict[str, Any] = yaml.safe_load(file)

    dataset_config = config["dataset"]
    sampling_config = config["sampling"]
    filtering_config = config["filtering"]
    allowed_licenses = set(config["license_policy"]["allow"])

    output_dir = Path("data/tokenizer")
    output_dir.mkdir(parents=True, exist_ok=True)

    train_limits = sampling_config["train_limits"]
    validation_limits = sampling_config["validation_limits"]

    states = {
        ("baseline", "train"): CorpusState(
            output_dir / "baseline_train.txt",
            train_limits["max_records"],
            train_limits["max_characters"],
        ),
        ("baseline", "validation"): CorpusState(
            output_dir / "baseline_validation.txt",
            validation_limits["max_records"],
            validation_limits["max_characters"],
        ),
        ("quality", "train"): CorpusState(
            output_dir / "quality_train.txt",
            train_limits["max_records"],
            train_limits["max_characters"],
        ),
        ("quality", "validation"): CorpusState(
            output_dir / "quality_validation.txt",
            validation_limits["max_records"],
            validation_limits["max_characters"],
        ),
    }

    for state in states.values():
        state.path.unlink(missing_ok=True)

    dataset = load_dataset(
        dataset_config["id"],
        split=dataset_config["split"],
        revision=dataset_config["revision"],
        streaming=True,
    )

    dataset = dataset.shuffle(
        seed=sampling_config["seed"],
        buffer_size=1000,
    )

    seen_hashes: set[str] = set()
    scanned = 0

    for record in dataset:
        if scanned >= sampling_config["scan_limit"]:
            break

        scanned += 1

        content_hash = record.get("hash")
        repo_name = record.get("repo_name")

        if content_hash is None:
            continue

        content_hash = str(content_hash)

        if not isinstance(repo_name, str) or not repo_name:
            continue

        if content_hash in seen_hashes:
            continue

        seen_hashes.add(content_hash)

        split = assign_split(
            record,
            seed=sampling_config["seed"],
            validation_fraction=sampling_config["validation_fraction"],
        )

        baseline = evaluate_common_requirements(record, allowed_licenses)
        quality = evaluate_quality_requirements(
            record,
            allowed_licenses,
            min_characters=filtering_config["min_characters"],
            max_characters=filtering_config["max_characters"],
            max_line_length=filtering_config["max_line_length"],
            allow_autogenerated=filtering_config["allow_autogenerated"],
        )

        content = record.get("content")

        if not isinstance(content, str):
            continue

        if baseline.accepted:
            states[("baseline", split)].add(content)

        if quality.accepted:
            states[("quality", split)].add(content)

        if scanned % 1000 == 0:
            print(f"Scanned {scanned}/{sampling_config['scan_limit']} records")

    print(f"\nFinished scanning {scanned} bounded records")

    for (experiment, split), state in states.items():
        print(
            f"{experiment:8} {split:10} "
            f"records={state.records:5} "
            f"characters={state.characters:10}"
        )


if __name__ == "__main__":
    main()