"""Pure functions for filtering streamed source-code records."""

from collections.abc import Collection
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class FilterDecision:
    """Result of applying a dataset filter."""

    accepted: bool
    reason: str


def normalize_license(value: Any) -> str:
    """Normalize a license value for reliable comparisons."""
    if not isinstance(value, str):
        return ""

    return value.strip().lower()


def evaluate_common_requirements(
    record: dict[str, Any],
    allowed_licenses: Collection[str],
) -> FilterDecision:
    """Apply requirements shared by every experiment."""
    content = record.get("content")

    if not isinstance(content, str):
        return FilterDecision(False, "content_not_string")

    if not content.strip():
        return FilterDecision(False, "content_empty")

    license_name = normalize_license(record.get("license"))
    normalized_allowlist = {normalize_license(item) for item in allowed_licenses}

    if not license_name:
        return FilterDecision(False, "license_missing")

    if license_name not in normalized_allowlist:
        return FilterDecision(False, "license_not_allowed")

    return FilterDecision(True, "accepted")


def evaluate_quality_requirements(
    record: dict[str, Any],
    allowed_licenses: Collection[str],
    *,
    min_characters: int,
    max_characters: int,
    max_line_length: int,
    allow_autogenerated: bool,
) -> FilterDecision:
    """Apply common requirements followed by additional quality checks."""
    common_decision = evaluate_common_requirements(
        record,
        allowed_licenses,
    )

    if not common_decision.accepted:
        return common_decision

    content = record["content"]
    content_length = len(content)

    if content_length < min_characters:
        return FilterDecision(False, "content_too_short")

    if content_length > max_characters:
        return FilterDecision(False, "content_too_long")

    if not allow_autogenerated and record.get("autogenerated") is True:
        return FilterDecision(False, "autogenerated")

    longest_line = max(
        (len(line) for line in content.splitlines()),
        default=0,
    )

    if longest_line > max_line_length:
        return FilterDecision(False, "line_too_long")

    return FilterDecision(True, "accepted")
